### ISSUE TITLE
Show effects still bugged

### ISSUE THREAD

**Issue by Siritachi31** [milbits/oldcord#158]
Hello, the new update fixed everything except the profiles. The profile picture of profiles is off centered from the rest of the profil, often being above or to the side of the center circle where it should be. everything else works fine again except this add on

**Comment by milbits** [comment]
fake news

**Comment by Siritachi31** [comment]
I'm not lying I literally copy pasted the import from the add on section and here's what happens

![Image](https://github.com/user-attachments/assets/6a207ad7-fa86-4c84-ae9a-b8be2ff6754a)

**Comment by milbits** [comment]
i fixed it 4 minutes ago btw

**Comment by Siritachi31** [comment]
I know and I literally JUST enabled it and it still happens while all the other issues are fixed. 

![Image](https://github.com/user-attachments/assets/788752de-27d4-4be8-8da3-c874549d6402)

**Comment by milbits** [comment]
did you try restarting discord

**Comment by Siritachi31** [comment]
Yes I just reset it twice and restarted my pc just to be safe it's still of center
Seems those with animated backgrounds or pfp are the ones affected most. a few static ones but mostly animated ones that are messed up

**Comment by milbits** [comment]
okay now it should be fixed

**Comment by Siritachi31** [comment]
Yup everything is working! Thank you so much for the quick fix and the theme overall! Appreciate it :D

**Comment by milbits** [comment]
:3
