### ISSUE TITLE
discord layout all fucked up, the close/X button at the top of the window goes offscreen even in windowed mode

### ISSUE THREAD

**Issue by crafter360** [milbits/oldcord#176]
![Image](https://github.com/user-attachments/assets/ddf720b4-dbe0-4f35-aa7b-7d0c43d5d1dd)

as you can see, the close button at the top doesnt work when oldcord is used

**Comment by EscapESC** [comment]
Should fix this, hopefully it will get merged quickly

**Comment by Halkiion** [comment]
the issue still exists for me and the "help" button seems to have disappeared off the edge too. I'm using Vencord

**Comment by KingGamingYT** [comment]
is this still an issue?

**Comment by jaltaer** [comment]
Also having the same issue. If I open the Settings window the top-right icons will appear normally but otherwise they're also cut off like OP's.

**Comment by Halkiion** [comment]
> is this still an issue?

for me it's fixed now. thank you
